-- Generated by Oracle SQL Developer Data Modeler 20.4.1.406.0906
--   at:        2021-06-09 21:52:09 BRT
--   site:      Oracle Database 11g
--   type:      Oracle Database 11g



-- predefined type, no DDL - MDSYS.SDO_GEOMETRY

-- predefined type, no DDL - XMLTYPE

CREATE TABLE atv_cli (
    id_ativ_cli         NUMBER NOT NULL,
    data_ultimo_acesso  DATE NOT NULL
);

ALTER TABLE atv_cli ADD CONSTRAINT atv_cli_pk PRIMARY KEY ( id_ativ_cli );

CREATE TABLE bairro (
    id_bairro         NUMBER NOT NULL,
    nome              VARCHAR2(100) NOT NULL,
    cidade_id_cidade  NUMBER NOT NULL
);

ALTER TABLE bairro ADD CONSTRAINT bairro_pk PRIMARY KEY ( id_bairro );

CREATE TABLE cidade (
    id_cidade         NUMBER NOT NULL,
    nome              VARCHAR2(100) NOT NULL,
    estado_id_estado  VARCHAR2(100) NOT NULL
);

ALTER TABLE cidade ADD CONSTRAINT cidade_pk PRIMARY KEY ( id_cidade );

CREATE TABLE cli_pro (
    cliente_id_cli              NUMBER NOT NULL,
    produto_id_pro              NUMBER NOT NULL,
    num_conta                   NUMBER NOT NULL,
    sta_cli_pro_id_sta_cli_pro  NUMBER NOT NULL,
    data_inicio                 DATE NOT NULL,
    data_termino                DATE NOT NULL
);

CREATE UNIQUE INDEX cli_pro__idx ON
    cli_pro (
        sta_cli_pro_id_sta_cli_pro
    ASC );

ALTER TABLE cli_pro ADD CONSTRAINT cli_pro_pk PRIMARY KEY ( produto_id_pro,
                                                            cliente_id_cli );

CREATE TABLE cliente (
    id_cli                 NUMBER NOT NULL,
    data_nascimento        DATE NOT NULL,
    cpf                    NUMBER NOT NULL,
    nome                   VARCHAR2(100) NOT NULL,
    sexo                   CHAR(1) NOT NULL,
    data_adesão            DATE NOT NULL,
    tip_cli_id_tip_cli     NUMBER NOT NULL,
    atv_cli_id_ativ_cli    NUMBER NOT NULL,
    estado_civil_id_civil  NUMBER NOT NULL,
    endereco_id_endereco   NUMBER NOT NULL,
    profissao_id_prof      NUMBER NOT NULL
);

CREATE UNIQUE INDEX cliente__idx ON
    cliente (
        atv_cli_id_ativ_cli
    ASC );

CREATE UNIQUE INDEX cliente__idxv1 ON
    cliente (
        estado_civil_id_civil
    ASC );

CREATE UNIQUE INDEX cliente__idxv2 ON
    cliente (
        endereco_id_endereco
    ASC );

CREATE UNIQUE INDEX cliente__idxv3 ON
    cliente (
        profissao_id_prof
    ASC );

CREATE UNIQUE INDEX cliente__idxv4 ON
    cliente (
        tip_cli_id_tip_cli
    ASC );

ALTER TABLE cliente ADD CONSTRAINT cliente_pk PRIMARY KEY ( id_cli );

CREATE TABLE dat_fun (
    id_dat_fun              NUMBER NOT NULL,
    hor_fun_id_hor_fun      NUMBER NOT NULL,
    dia_id_dia              NUMBER NOT NULL,
    estabelecimento_id_est  NUMBER NOT NULL
);

CREATE UNIQUE INDEX dat_fun__idx ON
    dat_fun (
        hor_fun_id_hor_fun
    ASC );

CREATE UNIQUE INDEX dat_fun__idxv1 ON
    dat_fun (
        estabelecimento_id_est
    ASC );

ALTER TABLE dat_fun ADD CONSTRAINT dat_fun_pk PRIMARY KEY ( id_dat_fun );

CREATE TABLE des_est (
    estabelecimento_id_est  NUMBER NOT NULL,
    foto                    BLOB NOT NULL,
    legenda                 VARCHAR2(100) NOT NULL,
    descricao               VARCHAR2(200) NOT NULL,
    especificacao           VARCHAR2(50)
);

ALTER TABLE des_est ADD CONSTRAINT des_est_pk PRIMARY KEY ( estabelecimento_id_est );

CREATE TABLE dia (
    id_dia  NUMBER NOT NULL,
    dia     VARCHAR2(20) NOT NULL
);

ALTER TABLE dia ADD CONSTRAINT dia_pk PRIMARY KEY ( id_dia );

CREATE TABLE dicas (
    id_dicas          NUMBER NOT NULL,
    descricao         CLOB NOT NULL,
    cidade_id_cidade  NUMBER NOT NULL
);

CREATE UNIQUE INDEX dicas__idx ON
    dicas (
        cidade_id_cidade
    ASC );

ALTER TABLE dicas ADD CONSTRAINT dicas_pk PRIMARY KEY ( id_dicas );

CREATE TABLE endereco (
    id_endereco               NUMBER NOT NULL,
    numero                    NUMBER NOT NULL,
    complemento               NUMBER,
    logradouro_id_logradouro  NUMBER NOT NULL
);

ALTER TABLE endereco ADD CONSTRAINT endereco_pk PRIMARY KEY ( id_endereco );

CREATE TABLE estabelecimento (
    id_est                NUMBER NOT NULL,
    nome                  VARCHAR2(100) NOT NULL,
    endereco_id_endereco  NUMBER NOT NULL,
    tipo_id_tip           NUMBER NOT NULL
);

CREATE UNIQUE INDEX estabelecimento__idx ON
    estabelecimento (
        endereco_id_endereco
    ASC );

ALTER TABLE estabelecimento ADD CONSTRAINT estabelecimento_pk PRIMARY KEY ( id_est );

CREATE TABLE estado (
    id_estado  VARCHAR2(100) NOT NULL,
    nome       VARCHAR2(100) NOT NULL,
    uf         VARCHAR2(2) NOT NULL
);

ALTER TABLE estado ADD CONSTRAINT estado_pk PRIMARY KEY ( id_estado );

CREATE TABLE estado_civil (
    id_civil   NUMBER NOT NULL,
    descrição  VARCHAR2(15) NOT NULL
);

ALTER TABLE estado_civil ADD CONSTRAINT estado_civil_pk PRIMARY KEY ( id_civil );

CREATE TABLE hor_fun (
    id_hor_fun  NUMBER NOT NULL,
    hor_abe     DATE NOT NULL,
    hor_fec     DATE NOT NULL
);

ALTER TABLE hor_fun ADD CONSTRAINT hor_fun_pk PRIMARY KEY ( id_hor_fun );

CREATE TABLE logradouro (
    id_logradouro     NUMBER NOT NULL,
    tipo              VARCHAR2(100) NOT NULL,
    nome              VARCHAR2(100) NOT NULL,
    bairro_id_bairro  NUMBER NOT NULL
);

ALTER TABLE logradouro ADD CONSTRAINT logradouro_pk PRIMARY KEY ( id_logradouro );

CREATE TABLE pro_est (
    id_pro_est              NUMBER NOT NULL,
    produto                 VARCHAR2(100) NOT NULL,
    quantidade              NUMBER NOT NULL,
    preco                   NUMBER NOT NULL,
    descricao               VARCHAR2(200) NOT NULL,
    estabelecimento_id_est  NUMBER NOT NULL
);

ALTER TABLE pro_est ADD CONSTRAINT pro_est_pk PRIMARY KEY ( id_pro_est );

CREATE TABLE produto (
    id_pro              NUMBER NOT NULL,
    nome                VARCHAR2(50) NOT NULL,
    descricao           VARCHAR2(50) NOT NULL,
    sta_pro_id_sta_pro  NUMBER NOT NULL,
    duracao_meses       NUMBER NOT NULL
);

CREATE UNIQUE INDEX produto__idx ON
    produto (
        sta_pro_id_sta_pro
    ASC );

ALTER TABLE produto ADD CONSTRAINT produto_pk PRIMARY KEY ( id_pro );

CREATE TABLE profissao (
    id_prof    NUMBER NOT NULL,
    descricao  VARCHAR2(50) NOT NULL
);

ALTER TABLE profissao ADD CONSTRAINT profissao_pk PRIMARY KEY ( id_prof );

CREATE TABLE sta_cli_pro (
    id_sta_cli_pro  NUMBER NOT NULL,
    descricao       VARCHAR2(50) NOT NULL
);

ALTER TABLE sta_cli_pro ADD CONSTRAINT sta_cli_pro_pk PRIMARY KEY ( id_sta_cli_pro );

CREATE TABLE sta_pro (
    id_sta_pro  NUMBER NOT NULL,
    descricao   VARCHAR2(50) NOT NULL
);

ALTER TABLE sta_pro ADD CONSTRAINT sta_pro_pk PRIMARY KEY ( id_sta_pro );

CREATE TABLE telefone (
    id_tel              NUMBER NOT NULL,
    tipo                NUMBER NOT NULL,
    numero              VARCHAR2(15) NOT NULL,
    cliente_id_cli      NUMBER NOT NULL,
    tip_tel_id_tip_tel  NUMBER NOT NULL
);

CREATE UNIQUE INDEX telefone__idx ON
    telefone (
        tip_tel_id_tip_tel
    ASC );

ALTER TABLE telefone ADD CONSTRAINT telefone_pk PRIMARY KEY ( id_tel );

CREATE TABLE tip_cli (
    id_tip_cli  NUMBER NOT NULL,
    nome        VARCHAR2(50) NOT NULL
);

ALTER TABLE tip_cli ADD CONSTRAINT tip_cli_pk PRIMARY KEY ( id_tip_cli );

CREATE TABLE tip_tel (
    id_tip_tel  NUMBER NOT NULL,
    descricao   VARCHAR2(20) NOT NULL
);

ALTER TABLE tip_tel ADD CONSTRAINT tip_tel_pk PRIMARY KEY ( id_tip_tel );

CREATE TABLE tipo (
    id_tip     NUMBER NOT NULL,
    descricao  VARCHAR2(50) NOT NULL
);

ALTER TABLE tipo ADD CONSTRAINT tipo_pk PRIMARY KEY ( id_tip );

CREATE TABLE visita (
    id_visita               NUMBER NOT NULL,
    data_visita             DATE NOT NULL,
    avaliacao               NUMBER,
    comentario              VARCHAR2(200),
    cliente_id_cli          NUMBER NOT NULL,
    estabelecimento_id_est  NUMBER NOT NULL
);

ALTER TABLE visita ADD CONSTRAINT visita_pk PRIMARY KEY ( id_visita );

ALTER TABLE bairro
    ADD CONSTRAINT bairro_cidade_fk FOREIGN KEY ( cidade_id_cidade )
        REFERENCES cidade ( id_cidade );

ALTER TABLE cidade
    ADD CONSTRAINT cidade_estado_fk FOREIGN KEY ( estado_id_estado )
        REFERENCES estado ( id_estado );

ALTER TABLE cli_pro
    ADD CONSTRAINT cli_pro_cliente_fk FOREIGN KEY ( cliente_id_cli )
        REFERENCES cliente ( id_cli );

ALTER TABLE cli_pro
    ADD CONSTRAINT cli_pro_produto_fk FOREIGN KEY ( produto_id_pro )
        REFERENCES produto ( id_pro );

ALTER TABLE cli_pro
    ADD CONSTRAINT cli_pro_sta_cli_pro_fk FOREIGN KEY ( sta_cli_pro_id_sta_cli_pro )
        REFERENCES sta_cli_pro ( id_sta_cli_pro );

ALTER TABLE cliente
    ADD CONSTRAINT cliente_atv_cli_fk FOREIGN KEY ( atv_cli_id_ativ_cli )
        REFERENCES atv_cli ( id_ativ_cli );

ALTER TABLE cliente
    ADD CONSTRAINT cliente_endereco_fk FOREIGN KEY ( endereco_id_endereco )
        REFERENCES endereco ( id_endereco );

ALTER TABLE cliente
    ADD CONSTRAINT cliente_estado_civil_fk FOREIGN KEY ( estado_civil_id_civil )
        REFERENCES estado_civil ( id_civil );

ALTER TABLE cliente
    ADD CONSTRAINT cliente_profissao_fk FOREIGN KEY ( profissao_id_prof )
        REFERENCES profissao ( id_prof );

ALTER TABLE cliente
    ADD CONSTRAINT cliente_tip_cli_fk FOREIGN KEY ( tip_cli_id_tip_cli )
        REFERENCES tip_cli ( id_tip_cli );

ALTER TABLE dat_fun
    ADD CONSTRAINT dat_fun_dia_fk FOREIGN KEY ( dia_id_dia )
        REFERENCES dia ( id_dia );

ALTER TABLE dat_fun
    ADD CONSTRAINT dat_fun_estabelecimento_fk FOREIGN KEY ( estabelecimento_id_est )
        REFERENCES estabelecimento ( id_est );

ALTER TABLE dat_fun
    ADD CONSTRAINT dat_fun_hor_fun_fk FOREIGN KEY ( hor_fun_id_hor_fun )
        REFERENCES hor_fun ( id_hor_fun );

ALTER TABLE des_est
    ADD CONSTRAINT des_est_estabelecimento_fk FOREIGN KEY ( estabelecimento_id_est )
        REFERENCES estabelecimento ( id_est );

ALTER TABLE dicas
    ADD CONSTRAINT dicas_cidade_fk FOREIGN KEY ( cidade_id_cidade )
        REFERENCES cidade ( id_cidade );

ALTER TABLE endereco
    ADD CONSTRAINT endereco_logradouro_fk FOREIGN KEY ( logradouro_id_logradouro )
        REFERENCES logradouro ( id_logradouro );

ALTER TABLE estabelecimento
    ADD CONSTRAINT estabelecimento_endereco_fk FOREIGN KEY ( endereco_id_endereco )
        REFERENCES endereco ( id_endereco );

ALTER TABLE estabelecimento
    ADD CONSTRAINT estabelecimento_tipo_fk FOREIGN KEY ( tipo_id_tip )
        REFERENCES tipo ( id_tip );

ALTER TABLE logradouro
    ADD CONSTRAINT logradouro_bairro_fk FOREIGN KEY ( bairro_id_bairro )
        REFERENCES bairro ( id_bairro );

ALTER TABLE pro_est
    ADD CONSTRAINT pro_est_estabelecimento_fk FOREIGN KEY ( estabelecimento_id_est )
        REFERENCES estabelecimento ( id_est );

ALTER TABLE produto
    ADD CONSTRAINT produto_sta_pro_fk FOREIGN KEY ( sta_pro_id_sta_pro )
        REFERENCES sta_pro ( id_sta_pro );

ALTER TABLE telefone
    ADD CONSTRAINT telefone_cliente_fk FOREIGN KEY ( cliente_id_cli )
        REFERENCES cliente ( id_cli );

ALTER TABLE telefone
    ADD CONSTRAINT telefone_tip_tel_fk FOREIGN KEY ( tip_tel_id_tip_tel )
        REFERENCES tip_tel ( id_tip_tel );

ALTER TABLE visita
    ADD CONSTRAINT visita_cliente_fk FOREIGN KEY ( cliente_id_cli )
        REFERENCES cliente ( id_cli );

ALTER TABLE visita
    ADD CONSTRAINT visita_estabelecimento_fk FOREIGN KEY ( estabelecimento_id_est )
        REFERENCES estabelecimento ( id_est );



-- Oracle SQL Developer Data Modeler Summary Report: 
-- 
-- CREATE TABLE                            25
-- CREATE INDEX                            12
-- ALTER TABLE                             50
-- CREATE VIEW                              0
-- ALTER VIEW                               0
-- CREATE PACKAGE                           0
-- CREATE PACKAGE BODY                      0
-- CREATE PROCEDURE                         0
-- CREATE FUNCTION                          0
-- CREATE TRIGGER                           0
-- ALTER TRIGGER                            0
-- CREATE COLLECTION TYPE                   0
-- CREATE STRUCTURED TYPE                   0
-- CREATE STRUCTURED TYPE BODY              0
-- CREATE CLUSTER                           0
-- CREATE CONTEXT                           0
-- CREATE DATABASE                          0
-- CREATE DIMENSION                         0
-- CREATE DIRECTORY                         0
-- CREATE DISK GROUP                        0
-- CREATE ROLE                              0
-- CREATE ROLLBACK SEGMENT                  0
-- CREATE SEQUENCE                          0
-- CREATE MATERIALIZED VIEW                 0
-- CREATE MATERIALIZED VIEW LOG             0
-- CREATE SYNONYM                           0
-- CREATE TABLESPACE                        0
-- CREATE USER                              0
-- 
-- DROP TABLESPACE                          0
-- DROP DATABASE                            0
-- 
-- REDACTION POLICY                         0
-- 
-- ORDS DROP SCHEMA                         0
-- ORDS ENABLE SCHEMA                       0
-- ORDS ENABLE OBJECT                       0
-- 
-- ERRORS                                   0
-- WARNINGS                                 0
