-- Generated by Oracle SQL Developer Data Modeler 20.4.0.374.0801
--   at:        2021-11-19 13:14:33 BRT
--   site:      Oracle Database 11g
--   type:      Oracle Database 11g



-- predefined type, no DDL - MDSYS.SDO_GEOMETRY

-- predefined type, no DDL - XMLTYPE
drop table estado cascade constraints;
drop table cidade cascade constraints;
drop table bairro cascade constraints;
drop table logradouro cascade constraints;
drop table endereco cascade constraints;
drop table noticiante cascade constraints;
drop table boletim cascade constraints;
drop table tip_bol cascade constraints;



-- Generated by Oracle SQL Developer Data Modeler 20.4.0.374.0801
--   at:        2021-11-19 13:29:45 BRT
--   site:      Oracle Database 11g
--   type:      Oracle Database 11g



-- predefined type, no DDL - MDSYS.SDO_GEOMETRY

-- predefined type, no DDL - XMLTYPE

CREATE TABLE bairro (
    cd_bairro  NUMBER(5) NOT NULL,
    nome       VARCHAR2(100) NOT NULL,
    cd_cidade  NUMBER(5) NOT NULL
);

ALTER TABLE bairro ADD CONSTRAINT bairro_pk PRIMARY KEY ( cd_bairro );

CREATE TABLE boletim (
    cd_boletim                NUMBER(5)
        CONSTRAINT nnc_boletim_cd_boletim NOT NULL,
    dt__inicio                DATE
        CONSTRAINT nnc_boletim_dt__inicio NOT NULL,
    dt_emissao                DATE
        CONSTRAINT nnc_boletim_dt_emissao NOT NULL,
    descricao                 VARCHAR2(500)
        CONSTRAINT nnc_boletim_descricao NOT NULL,
    endereco_cd_endereco      NUMBER(5) 
        CONSTRAINT nnc_boletim_cd_endereco NOT NULL,
    noticiante_cd_noticiante  NUMBER(5) 
        CONSTRAINT nnc_boletim_cd_noticiante NOT NULL,
    tip_bol_cd_tip_bol        NUMBER(5) 
        CONSTRAINT nnc_boletim_cd_tip_bol NOT NULL
);

ALTER TABLE boletim ADD CONSTRAINT boletim_pk PRIMARY KEY ( cd_boletim );

CREATE TABLE cidade (
    cd_cidade  NUMBER(5) NOT NULL,
    nome       VARCHAR2(100) NOT NULL,
    cd_estado  NUMBER(5) NOT NULL
);

ALTER TABLE cidade ADD CONSTRAINT cidade_pk PRIMARY KEY ( cd_cidade );

CREATE TABLE endereco (
    cd_endereco    NUMBER(5)
        CONSTRAINT nnc_endereco_cd_endereco NOT NULL,
    numero         NUMBER(10)
        CONSTRAINT nnc_endereco_numero NOT NULL,
    complemento    VARCHAR2(50),
    cd_logradouro  NUMBER(5)
        CONSTRAINT nnc_endereco_cd_logradouro NOT NULL
);

ALTER TABLE endereco ADD CONSTRAINT endereco_pk PRIMARY KEY ( cd_endereco );

CREATE TABLE estado (
    cd_estado  NUMBER(5) NOT NULL,
    nome       VARCHAR2(100) NOT NULL,
    uf         CHAR(2) NOT NULL
);

ALTER TABLE estado ADD CONSTRAINT estado_pk PRIMARY KEY ( cd_estado );

CREATE TABLE logradouro (
    cd_logradouro  NUMBER(5) NOT NULL,
    tipo           VARCHAR2(100) NOT NULL,
    nome           VARCHAR2(100) NOT NULL,
    cd_bairro      NUMBER(5) NOT NULL
);

ALTER TABLE logradouro ADD CONSTRAINT logradouro_pk PRIMARY KEY ( cd_logradouro );

CREATE TABLE noticiante (
    cd_noticiante  NUMBER(5) NOT NULL,
    dt_nascimento  DATE NOT NULL,
    cpf            CHAR(11) NOT NULL,
    nome           VARCHAR2(50) NOT NULL,
    sexo           CHAR(1) NOT NULL,
    constraint ck_noticiante_sexo CHECK(SEXO IN('F', 'f', 'M', 'm'))
);

ALTER TABLE noticiante ADD CONSTRAINT noticiante_pk PRIMARY KEY ( cd_noticiante );

CREATE TABLE tip_bol (
    cd_tip_bol  NUMBER(5) NOT NULL,
    descricao   VARCHAR2(50) NOT NULL
);

ALTER TABLE tip_bol ADD CONSTRAINT tipo_boletim_pk PRIMARY KEY ( cd_tip_bol );

ALTER TABLE bairro
    ADD CONSTRAINT bairro_cidade_fk FOREIGN KEY ( cd_cidade )
        REFERENCES cidade ( cd_cidade );

ALTER TABLE boletim
    ADD CONSTRAINT boletim_endereco_fk FOREIGN KEY ( endereco_cd_endereco )
        REFERENCES endereco ( cd_endereco );

ALTER TABLE boletim
    ADD CONSTRAINT boletim_noticiante_fk FOREIGN KEY ( noticiante_cd_noticiante )
        REFERENCES noticiante ( cd_noticiante );

ALTER TABLE boletim
    ADD CONSTRAINT boletim_tip_bol_fk FOREIGN KEY ( tip_bol_cd_tip_bol )
        REFERENCES tip_bol ( cd_tip_bol );

ALTER TABLE cidade
    ADD CONSTRAINT cidade_estado_fk FOREIGN KEY ( cd_estado )
        REFERENCES estado ( cd_estado );

ALTER TABLE endereco
    ADD CONSTRAINT endereco_logradouro_fk FOREIGN KEY ( cd_logradouro )
        REFERENCES logradouro ( cd_logradouro );

ALTER TABLE logradouro
    ADD CONSTRAINT logradouro_bairro_fk FOREIGN KEY ( cd_bairro )
        REFERENCES bairro ( cd_bairro );



-- Oracle SQL Developer Data Modeler Summary Report: 
-- 
-- CREATE TABLE                             8
-- CREATE INDEX                             0
-- ALTER TABLE                             15
-- CREATE VIEW                              0
-- ALTER VIEW                               0
-- CREATE PACKAGE                           0
-- CREATE PACKAGE BODY                      0
-- CREATE PROCEDURE                         0
-- CREATE FUNCTION                          0
-- CREATE TRIGGER                           0
-- ALTER TRIGGER                            0
-- CREATE COLLECTION TYPE                   0
-- CREATE STRUCTURED TYPE                   0
-- CREATE STRUCTURED TYPE BODY              0
-- CREATE CLUSTER                           0
-- CREATE CONTEXT                           0
-- CREATE DATABASE                          0
-- CREATE DIMENSION                         0
-- CREATE DIRECTORY                         0
-- CREATE DISK GROUP                        0
-- CREATE ROLE                              0
-- CREATE ROLLBACK SEGMENT                  0
-- CREATE SEQUENCE                          0
-- CREATE MATERIALIZED VIEW                 0
-- CREATE MATERIALIZED VIEW LOG             0
-- CREATE SYNONYM                           0
-- CREATE TABLESPACE                        0
-- CREATE USER                              0
-- 
-- DROP TABLESPACE                          0
-- DROP DATABASE                            0
-- 
-- REDACTION POLICY                         0
-- 
-- ORDS DROP SCHEMA                         0
-- ORDS ENABLE SCHEMA                       0
-- ORDS ENABLE OBJECT                       0
-- 
-- ERRORS                                   0
-- WARNINGS                                 0

